### PR TITLE
upload rate when seeding, unsufficient free space warning only, remove GA tracking files

### PR DESCRIPTION
**Pull request by scakemyer**
- don't share whole HOME folder with docker build process
- build for windows_x64 since libtorrent-go has it too (untested)

### CODE REVIEW

**Comment by scakemyer** [comment]
Nah, it's just leftover cruft really

**Comment by scakemyer** [comment]
Not getting rid of download rate at all. Just showing upload rate when seeding since the download rate drops close to zero by then. I agree that showing both would be better.

Also not removing the size checking, just not bailing when it doesn't pass because it doesn't account for already downloaded parts. If you have 4GB available, start downloading a 3GB file, stop at 2GB, and try to resume, it will fail because it still wants the full 3GB. Until we fix it by using `status.GetTotal_done()` later on instead of as soon as receiving metadata, commenting those two lines is the better option here.

**Comment by i96751414** [comment]
Ah alright. Thanks for your explanation!

**Comment by scakemyer** [comment]
It's already clear if it's downloading or uploading, it shows "Buffering" or "Seeding"... But as I said, I agree that showing both is better so pushing that change right now.

For the size checking issue, we might have so subscribe to another alert channel from libtorrent depending on when the currently downloaded size is available. We could also go a step further and allow downloading up to a certain point (with a notification) and only then pausing the download, prompting the user to free some space before resuming.

**Pull request closed without merging**
